var products = [
  {
    id: 0,
    title: "-- Select Anyone --",
    price: "",
    description: "",
    brand: "",
    genre: "",
    imageSrc: "./Assets/Images/medium Card Size/No_Image.png",
    requirements: {
      ram: "",
      gpu: "",
      cpu: "",
      hdd: "",
    },
  },
  {
    id: 1,
    title: "CyberPunk",
    price: "59.99",
    description:
      "CyberPunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour, and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality. Customize your character’s cyberware, skillset, and playstyle, and explore a vast city where the choices you make shape the story and the world around you.",
    brand: "CD Projekt",
    genre: "RPG",
    imageSrc: "./Assets/Images/medium Card Size/CyberPunk.jpg",
    requirements: {
      ram: "16GB",
      gpu: "NVIDIA GTX 1060",
      cpu: "Intel i7-4790",
      hdd: "70GB",
    },
  },
  {
    id: 2,
    title: "Call Of Duty: Modern Warfare 3",
    price: "39.99",
    description:
      "Call Of Duty: Modern Warfare 3 is a first-person shooter video game that takes place across various international locations. Players take on the roles of multiple characters in a narrative-driven campaign, experience intense multiplayer modes, and enjoy cooperative Special Ops missions. The game features a diverse range of weapons, explosive set-pieces, and a gripping story that keeps players on the edge of their seats.",
    brand: "Activision",
    genre: "FPS",
    imageSrc: "./Assets/Images/medium Card Size/CallOfDutyMW3.jpg",
    requirements: {
      ram: "4GB",
      gpu: "NVIDIA GTS 450",
      cpu: "Intel Core 2 Duo E6600",
      hdd: "16GB",
    },
  },
  {
    id: 3,
    title: "Fifa 24",
    price: "49.99",
    description:
      "Fifa 24 brings the world’s game to life with realistic graphics, immersive gameplay, and all the latest teams and leagues. Experience the thrill of football with enhanced ball physics, intelligent AI, and dynamic tactics. Play through various modes, including Career, Ultimate Team, and Volta Football, and compete against players worldwide in online matches.",
    brand: "EA Sports",
    genre: "Sports",
    imageSrc: "./Assets/Images/medium Card Size/Fifa24.jpeg",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 660",
      cpu: "Intel i3-6100",
      hdd: "50GB",
    },
  },
  {
    id: 4,
    title: "Among Us",
    price: "4.99",
    description:
      "Among Us is a multiplayer party game where players work together to complete tasks on a spaceship while trying to root out the impostors among them. Impostors aim to sabotage the mission and eliminate crewmates without being detected. The game emphasizes communication, deception, and teamwork, offering endless fun in both local and online multiplayer modes.",
    brand: "Innersloth",
    genre: "Party",
    imageSrc: "./Assets/Images/medium Card Size/AmongUs.jpeg",
    requirements: {
      ram: "1GB",
      gpu: "Integrated",
      cpu: "Intel Pentium 4",
      hdd: "250MB",
    },
  },
  {
    id: 5,
    title: "Ghost Of Tsushima",
    price: "59.99",
    description:
      "Ghost Of Tsushima is an open-world action-adventure game set in feudal Japan. Players control Jin Sakai, a samurai warrior on a quest to protect his homeland from Mongol invaders. The game features stunning landscapes, fluid combat mechanics, and a rich storyline that delves into themes of honor, sacrifice, and resilience. Explore a vast, dynamic world filled with quests, secrets, and immersive experiences.",
    brand: "Sony Interactive Entertainment",
    genre: "Action-Adventure",
    imageSrc: "./Assets/Images/medium Card Size/GhostOfTsushima.jpg",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 950",
      cpu: "Intel i5-2500K",
      hdd: "50GB",
    },
  },
  {
    id: 6,
    title: "Dead By Daylight 4",
    price: "19.99",
    description:
      "Dead By Daylight 4 is a multiplayer horror game where one player takes on the role of a savage killer and the other four players are survivors trying to escape. The game offers a wide variety of killers and survivors, each with unique abilities and perks. The gameplay is intense, strategic, and filled with jump scares, making it a thrilling experience for fans of horror and survival games.",
    brand: "Behaviour Interactive",
    genre: "Horror",
    imageSrc: "./Assets/Images/medium Card Size/DeadByDaylight4.jpeg",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 760",
      cpu: "Intel Core i3-4170",
      hdd: "50GB",
    },
  },
  {
    id: 7,
    title: "Code Of War",
    price: "29.99",
    description:
      "Code Of War is a third-person action game set in a post-apocalyptic world where players must navigate through hostile environments and battle various enemies. The game features intense combat, strategic gameplay, and a gripping storyline that immerses players in a world of chaos and survival. With a wide range of weapons, upgrades, and skills, players can customize their approach to each encounter.",
    brand: "COW Studios",
    genre: "Action",
    imageSrc: "./Assets/Images/medium Card Size/CodeOfWar.jpeg",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 970",
      cpu: "Intel Core i5-6600K",
      hdd: "30GB",
    },
  },
  {
    id: 8,
    title: "Destiny 2",
    price: "49.99",
    description:
      "Destiny 2 is an online-only multiplayer first-person shooter with role-playing and MMO elements. Players, known as Guardians, are tasked with protecting Earth's last safe city from alien races. The game features cooperative 'Strikes,' player-versus-player modes, and 'Raids' that require team coordination and strategy. With an evolving storyline, dynamic events, and extensive lore, Destiny 2 offers an expansive and immersive experience.",
    brand: "Bungie",
    genre: "FPS",
    imageSrc: "./Assets/Images/medium Card Size/Destiny2.jpg",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 1050",
      cpu: "Intel Core i3-3250",
      hdd: "105GB",
    },
  },
  {
    id: 9,
    title: "Dead Rising 4",
    price: "29.99",
    description:
      "Dead Rising 4 is an action-adventure game where players fight off hordes of zombies in a sandbox environment. The game features an open world, a wide variety of weapons and vehicles, and an over-the-top sense of humor. Players can customize their character, complete various missions, and explore different areas while battling the undead and uncovering the story behind the outbreak.",
    brand: "Capcom",
    genre: "Action",
    imageSrc: "./Assets/Images/medium Card Size/DeadRising4.jpeg",
    requirements: {
      ram: "6GB",
      gpu: "NVIDIA GTX 970",
      cpu: "Intel i5-2400",
      hdd: "50GB",
    },
  },
  {
    id: 10,
    title: "Elden Ring",
    price: "59.99",
    description:
      "Elden Ring is an action RPG developed by FromSoftware, known for its rich lore, challenging gameplay, and intricate world design. Players explore a vast, open world filled with danger, mystery, and discovery. With a deep combat system, diverse character builds, and a narrative co-created by George R.R. Martin, Elden Ring offers an unforgettable experience for fans of the genre.",
    brand: "FromSoftware",
    genre: "RPG",
    imageSrc: "./Assets/Images/medium Card Size/EldenRing.jpg",
    requirements: {
      ram: "16GB",
      gpu: "NVIDIA GTX 1080",
      cpu: "Intel i7-8700K",
      hdd: "80GB",
    },
  },
  {
    id: 11,
    title: "AC Shadow",
    price: "39.99",
    description:
      "AC Shadow is a stealth-action game where players take on the role of an assassin navigating through historical settings. The game features intricate parkour mechanics, a variety of weapons and tools, and a rich storyline that intertwines with real historical events. Players can explore open-world environments, complete missions, and uncover secrets while eliminating targets in creative and strategic ways.",
    brand: "Ubisoft",
    genre: "Action-Adventure",
    imageSrc: "./Assets/Images/medium Card Size/ACShadow.png",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 780",
      cpu: "Intel i5-2500K",
      hdd: "45GB",
    },
  },
  {
    id: 12,
    title: "Brother In Arms",
    price: "19.99",
    description:
      "Brother In Arms is a tactical shooter game that immerses players in the gritty and intense battles of World War II. The game emphasizes squad-based tactics and realistic combat scenarios. Players lead a team of soldiers through historically accurate missions, making strategic decisions to achieve objectives. The game features detailed environments, authentic weaponry, and a compelling storyline that highlights the heroism and sacrifice of soldiers.",
    brand: "Gearbox Software",
    genre: "Tactical Shooter",
    imageSrc: "./Assets/Images/medium Card Size/BrotherInArms.jpg",
    requirements: {
      ram: "2GB",
      gpu: "NVIDIA GeForce 6800",
      cpu: "Intel Pentium 4",
      hdd: "5GB",
    },
  },
  {
    id: 13,
    title: "Call Of Duty: Modern Warfare 1",
    price: "39.99",
    description:
      "Call Of Duty: Modern Warfare 1 is a groundbreaking first-person shooter that redefined the genre. The game offers a compelling single-player campaign set in various global locations, along with a robust multiplayer mode featuring diverse maps and game modes. Players experience intense, fast-paced combat with a wide array of weapons and tactical equipment, making it a staple in the FPS genre.",
    brand: "Activision",
    genre: "FPS",
    imageSrc: "./Assets/Images/medium Card Size/CallOfDutyMW1.jpg",
    requirements: {
      ram: "2GB",
      gpu: "NVIDIA GeForce 6600",
      cpu: "Intel Pentium 4",
      hdd: "8GB",
    },
  },
  {
    id: 14,
    title: "ANNO",
    price: "29.99",
    description:
      "ANNO is a city-building and economic simulation game where players manage resources, build cities, and develop trade routes. The game spans different historical periods, offering unique challenges and opportunities. Players must balance their economy, handle diplomatic relations, and expand their empire while ensuring the well-being of their citizens. ANNO combines strategic planning with creative city-building in an immersive and engaging experience.",
    brand: "Ubisoft",
    genre: "Simulation",
    imageSrc: "./Assets/Images/medium Card Size/ANNO.png",
    requirements: {
      ram: "4GB",
      gpu: "NVIDIA GeForce GTX 660",
      cpu: "Intel i5-2400",
      hdd: "20GB",
    },
  },
  {
    id: 15,
    title: "Far Cry 3",
    price: "29.99",
    description:
      "Far Cry 3 is an open-world first-person shooter set on a tropical island. Players assume the role of Jason Brody, a tourist stranded on the island who must rescue his friends and escape from the clutches of a psychotic warlord. The game features a vast, explorable world filled with wildlife, side missions, and dynamic encounters. Players can use a variety of weapons and tactics to survive in this hostile environment.",
    brand: "Ubisoft",
    genre: "FPS",
    imageSrc: "./Assets/Images/medium Card Size/FarCry3.jpg",
    requirements: {
      ram: "4GB",
      gpu: "NVIDIA GeForce GTX 460",
      cpu: "Intel Core 2 Duo E6700",
      hdd: "15GB",
    },
  },
  {
    id: 16,
    title: "Forza Horizon 5",
    price: "59.99",
    description:
      "Forza Horizon 5 is an open-world racing game set in a stunning representation of Mexico. The game features a diverse range of cars, dynamic weather, and a variety of racing events. Players can explore the vast landscape, participate in street races, off-road adventures, and showcase events. With a detailed car customization system and online multiplayer, Forza Horizon 5 offers an exhilarating experience for racing enthusiasts.",
    brand: "Microsoft",
    genre: "Racing",
    imageSrc: "./Assets/Images/medium Card Size/ForzaHorizon5.jpeg",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 970",
      cpu: "Intel i5-4460",
      hdd: "80GB",
    },
  },
  {
    id: 17,
    title: "Flight Simulator",
    price: "59.99",
    description:
      "Flight Simulator is a comprehensive flight simulation game that offers an incredibly realistic flying experience. Players can pilot a wide variety of aircraft, from light planes to commercial jets, and explore the entire globe with detailed and dynamic weather systems. The game features stunning graphics, accurate aerodynamics, and real-time air traffic, making it a must-play for aviation enthusiasts.",
    brand: "Microsoft",
    genre: "Simulation",
    imageSrc: "./Assets/Images/medium Card Size/FlightSimulator.png",
    requirements: {
      ram: "16GB",
      gpu: "NVIDIA GTX 970",
      cpu: "Intel i5-8400",
      hdd: "150GB",
    },
  },
  {
    id: 18,
    title: "Forza Motorsport",
    price: "59.99",
    description:
      "Forza Motorsport is a racing simulation game that focuses on delivering a realistic and immersive racing experience. The game features a wide range of meticulously detailed cars and tracks, advanced physics, and dynamic weather conditions. Players can participate in various racing events, customize their vehicles, and compete against others in online multiplayer. Forza Motorsport sets the standard for simulation racing games.",
    brand: "Microsoft",
    genre: "Racing",
    imageSrc: "./Assets/Images/medium Card Size/ForzaMotorSport.jpeg",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 970",
      cpu: "Intel i5-4460",
      hdd: "80GB",
    },
  },
  {
    id: 19,
    title: "Cricket 24",
    price: "49.99",
    description:
      "Cricket 24 brings the excitement of cricket to life with realistic gameplay, detailed player models, and authentic stadiums. The game features various modes, including career, tournaments, and multiplayer. Players can experience the thrill of batting, bowling, and fielding with accurate physics and strategic depth. Cricket 24 is a must-have for cricket fans looking for an immersive and enjoyable cricketing experience.",
    brand: "Big Ant Studios",
    genre: "Sports",
    imageSrc: "./Assets/Images/medium Card Size/Cricket24.jpeg",
    requirements: {
      ram: "8GB",
      gpu: "NVIDIA GTX 660",
      cpu: "Intel i3-3210",
      hdd: "30GB",
    },
  },
  {
    id: 20,
    title: "Prince of Persia",
    price: "19.99",
    description:
      "Prince of Persia is an iconic action-adventure game where players take on the role of the Prince, who embarks on a quest to save the kingdom from darkness. Known for its fluid parkour-style gameplay, the game features stunning acrobatic moves and intense combat sequences. Navigate through ancient palaces, solve puzzles, and battle mythical creatures in this epic tale of heroism and redemption. With its captivating storyline and breathtaking visuals, Prince of Persia remains a timeless classic in the gaming world.",
    brand: "Ubisoft",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/PrinceOfPersia.png",
    requirements: {
      ram: "2 GB",
      gpu: "512 MB DirectX 9 compatible",
      cpu: "Intel Core 2 Duo 2.4GHz, AMD Athlon X2 2.8GHz",
      hdd: "8 GB",
    },
  },
  {
    id: 21,
    title: "Minecraft",
    price: "24.99",
    description:
      "Minecraft is a sandbox game that allows players to build and explore virtual worlds made up of blocks. With endless possibilities and creative freedom, players can craft tools, construct buildings, and mine resources in a pixelated universe. Survive against creatures like zombies and spiders during the night, and collaborate with friends to create elaborate structures. With its simplistic yet engaging gameplay, Minecraft has become a global phenomenon, attracting millions of players of all ages. Immerse yourself in a world where your imagination is the only limit, and embark on adventures that are as vast as your creativity.",
    brand: "Mojang Studios",
    genre: "Sandbox, Survival",
    imageSrc: "./Assets/Images/medium Card Size/Minecraft.jpg",
    requirements: {
      ram: "4 GB",
      gpu: "Integrated: Intel HD Graphics 4000 (Ivy Bridge) or AMD Radeon R5 series (Kaveri line) with OpenGL 4.4",
      cpu: "Intel Core i3-3210 3.2 GHz / AMD A8-7600 APU 3.1 GHz or equivalent",
      hdd: "4 GB",
    },
  },
  {
    id: 22,
    title: "Horizon Forbidden West",
    price: "59.99",
    description:
      "Horizon Forbidden West continues the journey of Aloy, a young hunter in a world overrun by robotic creatures. Set in a post-apocalyptic America, Aloy ventures to the western frontier to uncover mysteries of the past and confront new threats. With stunning visuals and a vast open world to explore, the game offers a blend of action, exploration, and storytelling. Engage in dynamic combat using a variety of weapons and tactics, and discover ancient ruins and futuristic cities as you unravel the secrets of a lost civilization. Horizon Forbidden West promises an immersive experience filled with adventure and discovery.",
    brand: "Guerrilla Games",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/HorizonForbiddenWest.jpg",
    requirements: {
      ram: "16 GB",
      gpu: "NVIDIA GeForce GTX 1660 / AMD Radeon RX 590",
      cpu: "Intel Core i7-4770K / AMD Ryzen 5 1500X",
      hdd: "70 GB",
    },
  },
  {
    id: 23,
    title: "Max Payne",
    price: "14.99",
    description:
      "Max Payne is a neo-noir action-thriller game that follows the story of Max Payne, a former NYPD detective turned vigilante. Hunted by the police and the mob, Max seeks vengeance for the murder of his family while uncovering a conspiracy that goes deeper than he ever imagined. With its innovative 'Bullet Time' gameplay mechanic, players can slow down time during intense gunfights, making every bullet count. Navigate through dark and gritty environments, solve puzzles, and survive against overwhelming odds in this gripping tale of betrayal and redemption.",
    brand: "Remedy Entertainment",
    genre: "Action, Shooter",
    imageSrc: "./Assets/Images/medium Card Size/MaxPayne.jpg",
    requirements: {
      ram: "512 MB",
      gpu: "DirectX 9 compatible",
      cpu: "Pentium III 1 GHz or Athlon equivalent",
      hdd: "1.5 GB",
    },
  },
  {
    id: 24,
    title: "Killing Floor 2",
    price: "29.99",
    description:
      "Killing Floor 2 is a cooperative first-person shooter where players team up to fight against hordes of mutated creatures created by a biotech corporation. Set in diverse environments ranging from European cities to scientific facilities, the game offers intense action and strategic gameplay. Choose from multiple classes, each with unique abilities and weapons, and work together to survive increasingly challenging waves of enemies. With its detailed gore system and dynamic difficulty scaling, Killing Floor 2 delivers a thrilling and replayable experience for fans of cooperative shooters.",
    brand: "Tripwire Interactive",
    genre: "First-person shooter, Survival horror",
    imageSrc: "./Assets/Images/medium Card Size/KillingFloor2.jpeg",
    requirements: {
      ram: "4 GB",
      gpu: "NVIDIA GeForce GTX 560 / AMD Radeon HD 6950",
      cpu: "Core 2 Duo E8200 2.66GHz / Phenom II X2 545",
      hdd: "50 GB",
    },
  },
  {
    id: 26,
    title: "NBK2k24",
    price: "49.99",
    description:
      "NBK2k24 is a basketball simulation game that offers a realistic NBA experience, allowing players to control their favorite teams and players on the court. With updated rosters, improved graphics, and enhanced gameplay mechanics, NBK2k24 delivers an immersive basketball simulation. Engage in fast-paced matches, compete in tournaments, and build your dream team as you strive for championship glory. With its detailed player animations and strategic depth, NBK2k24 is a must-have for basketball fans and sports enthusiasts alike.",
    brand: "2K Sports",
    genre: "Sports, Simulation",
    imageSrc: "./Assets/Images/medium Card Size/NBK2k24.jpg",
    requirements: {
      ram: "4 GB",
      gpu: "NVIDIA GeForce GTX 770 / AMD Radeon R9 270",
      cpu: "Intel Core i5-4430 / AMD FX-8370",
      hdd: "100 GB",
    },
  },
  {
    id: 27,
    title: "Lies of P",
    price: "34.99",
    description:
      "Lies of P is a narrative-driven action RPG that combines deep storytelling with fast-paced combat and exploration. Set in a fantastical world where magic and technology coexist, players take on the role of a young hero destined to uncover ancient secrets and confront powerful adversaries. With its branching narrative and moral choices, Lies of P offers a dynamic gameplay experience where every decision shapes the outcome of the story. Master various combat styles, solve intricate puzzles, and forge alliances as you embark on an epic journey filled with mystery and adventure.",
    brand: "Obsidian Entertainment",
    genre: "Action, RPG",
    imageSrc: "./Assets/Images/medium Card Size/LiesOfP.jpeg",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 1060 / AMD Radeon RX 580",
      cpu: "Intel Core i5-7600K / AMD Ryzen 5 1600X",
      hdd: "50 GB",
    },
  },
  {
    id: 28,
    title: "Medal of Honor",
    price: "29.99",
    description:
      "Medal of Honor is a first-person shooter set during World War II, where players assume the role of a member of the Allied forces battling against the Axis powers. Engage in historic battles across Europe, from the beaches of Normandy to the heart of Germany, and experience the intensity and heroism of the war. With its cinematic storytelling and realistic gameplay, Medal of Honor immerses players in the challenges faced by soldiers during one of history's darkest periods. Use authentic weapons, navigate through war-torn landscapes, and honor the sacrifices of those who fought for freedom.",
    brand: "Electronic Arts",
    genre: "First-person shooter",
    imageSrc: "./Assets/Images/medium Card Size/MedalOfHonor.jpg",
    requirements: {
      ram: "1 GB",
      gpu: "NVIDIA GeForce 6600 GT / ATI Radeon X1300",
      cpu: "Intel Pentium 4 2.8 GHz / AMD Athlon XP 2800+",
      hdd: "9 GB",
    },
  },
  {
    id: 29,
    title: "Palworld",
    price: "39.99",
    description:
      "Palworld is an open-world sandbox game where players explore a vibrant and magical world inhabited by creatures known as Pals. Capture, train, and bond with Pals to help you on your adventures, whether it's exploring dungeons, building settlements, or embarking on quests. With its blend of resource management, crafting, and creature-raising mechanics, Palworld offers a unique gameplay experience that encourages creativity and exploration. Customize your character, build relationships with Pals, and uncover the secrets of this enchanting world.",
    brand: "Pocketpair",
    genre: "Open-world, Sandbox",
    imageSrc: "./Assets/Images/medium Card Size/Palworld.jpg",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 1060 / AMD Radeon RX 580",
      cpu: "Intel Core i5-7500 / AMD Ryzen 5 1600",
      hdd: "20 GB",
    },
  },
  {
    id: 30,
    title: "Hitman",
    price: "49.99",
    description:
      "Hitman is a stealth action game where players assume the role of Agent 47, a genetically enhanced assassin tasked with eliminating high-profile targets across the globe. Utilize a variety of weapons, disguises, and stealth tactics to infiltrate secure locations and execute precise assassinations. With its sandbox-style gameplay and intricate level designs, Hitman offers endless opportunities for creative and strategic gameplay. Plan your approach, adapt to changing situations, and immerse yourself in a world of espionage and intrigue.",
    brand: "IO Interactive",
    genre: "Stealth, Action",
    imageSrc: "./Assets/Images/medium Card Size/Hitman.jpg",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 660 / AMD Radeon HD 7870",
      cpu: "Intel Core i5-2500K / AMD Phenom II X4 940",
      hdd: "60 GB",
    },
  },
  {
    id: 31,
    title: "NFS Rivals",
    price: "39.99",
    description:
      "Need for Speed Rivals is a high-octane racing game that pits players against each other in intense street races and police pursuits. Set in the fictional Redview County, the game offers a seamless blend of single-player and multiplayer experiences. Choose to play as a racer or a cop, each with their own unique challenges and abilities. Customize your car with performance upgrades and visual modifications, and compete for dominance in an open-world environment filled with thrilling races and adrenaline-pumping pursuits.",
    brand: "Electronic Arts",
    genre: "Racing",
    imageSrc: "./Assets/Images/medium Card Size/NFSRivals.jpg",
    requirements: {
      ram: "4 GB",
      gpu: "NVIDIA GeForce GTX 560 / AMD Radeon HD 6950",
      cpu: "Intel Core 2 Duo 2.4 GHz / AMD Athlon X2 2.8 GHz",
      hdd: "30 GB",
    },
  },
  {
    id: 32,
    title: "Plants vs. Zombies",
    price: "9.99",
    description:
      "Plants vs. Zombies is a tower defense game where players defend their homes from a zombie invasion using an arsenal of plants with unique abilities. Strategically place plants to fend off waves of zombies across different environments, from your backyard to the roof of your house. With its charming graphics and addictive gameplay, Plants vs. Zombies offers a lighthearted yet challenging experience for players of all ages. Unlock new plants, discover powerful upgrades, and test your strategy in endless survival modes.",
    brand: "PopCap Games",
    genre: "Tower defense",
    imageSrc: "./Assets/Images/medium Card Size/PlantvsZombies.jpg",
    requirements: {
      ram: "1 GB",
      gpu: "NVIDIA GeForce 6600 / ATI Radeon X1300",
      cpu: "1.2 GHz",
      hdd: "65 MB",
    },
  },
  {
    id: 33,
    title: "Minecraft Dungeons",
    price: "19.99",
    description:
      "Minecraft Dungeons is an action-adventure game set in the Minecraft universe, offering a new perspective on the classic blocky world. Battle hordes of monsters, explore procedurally generated dungeons, and uncover powerful artifacts as you embark on a quest to defeat the evil Arch-Illager. With its cooperative multiplayer mode, players can team up with friends to tackle challenges and explore dungeons together. Collect loot, customize your gear, and discover new abilities in this family-friendly dungeon crawler that combines action and strategy.",
    brand: "Mojang Studios",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/MincraftDungeons.jpg",
    requirements: {
      ram: "2 GB",
      gpu: "NVIDIA GeForce GTX 650 / AMD Radeon HD 7850",
      cpu: "Intel Core i5-4690 / AMD A10-7800",
      hdd: "6 GB",
    },
  },
  {
    id: 34,
    title: "Red Dead Redemption 2",
    price: "59.99",
    description:
      "Red Dead Redemption 2 is an epic Western-themed action-adventure game set in a vast and atmospheric open world. Players assume the role of Arthur Morgan, a member of the Van der Linde gang, as he navigates the challenges of life on the American frontier. Engage in gunfights, hunt wildlife, and interact with a cast of memorable characters in a narrative-driven experience. With its stunning visuals, immersive gameplay, and detailed world-building, Red Dead Redemption 2 offers an unforgettable journey through the Wild West.",
    brand: "Rockstar Games",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/RedDeadRedemption2.webp",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 770 2GB / AMD Radeon R9 280 3GB",
      cpu: "Intel Core i5-2500K / AMD FX-6300",
      hdd: "150 GB",
    },
  },
  {
    id: 35,
    title: "Resident Evil 3",
    price: "39.99",
    description:
      "Resident Evil 3 is a survival horror game that follows Jill Valentine as she tries to escape the zombie-infested Raccoon City. As the deadly T-virus spreads, Jill must navigate through perilous environments, solve puzzles, and evade terrifying enemies like the relentless Nemesis. With its intense action sequences and harrowing atmosphere, Resident Evil 3 delivers heart-pounding suspense and adrenaline-pumping horror. Uncover the secrets of Umbrella Corporation and survive against all odds in this gripping remake of a classic survival horror masterpiece.",
    brand: "Capcom",
    genre: "Survival Horror",
    imageSrc: "./Assets/Images/medium Card Size/ResidentEvil3.jpeg",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 1060 / AMD Radeon RX 580",
      cpu: "Intel Core i5-4460 / AMD FX-6300",
      hdd: "45 GB",
    },
  },
  {
    id: 36,
    title: "Robin Hood",
    price: "29.99",
    description:
      "Robin Hood is an action-adventure game that brings to life the legendary tale of the heroic outlaw. Play as Robin Hood and his band of Merry Men as they fight against tyranny and injustice in medieval England. Engage in daring heists, ambush enemy patrols, and navigate through Sherwood Forest in this thrilling adventure. With its emphasis on stealth, strategy, and moral choices, Robin Hood offers players the chance to become the folk hero of Nottinghamshire and inspire the oppressed to rise against their oppressors.",
    brand: "Unknown",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/RobinHood.jpeg",
    requirements: {
      ram: "4 GB",
      gpu: "NVIDIA GeForce GTX 660 / AMD Radeon HD 7870",
      cpu: "Intel Core i3-2100 / AMD FX-6300",
      hdd: "20 GB",
    },
  },
  {
    id: 37,
    title: "Roblox",
    price: "Free to Play",
    description:
      "Roblox is an online platform that allows players to create and share games with others in a virtual universe. With millions of user-generated games to explore, ranging from simulations and role-playing adventures to obstacle courses and multiplayer competitions, Roblox offers endless entertainment for players of all ages. Customize your avatar, build your own games using the intuitive Roblox Studio, and collaborate with friends in immersive 3D experiences. Whether you're a creator or a player, Roblox encourages creativity, social interaction, and community engagement.",
    brand: "Roblox Corporation",
    genre: "Platform, User-generated content",
    imageSrc: "./Assets/Images/medium Card Size/Roblox.jpeg",
    requirements: {
      ram: "1 GB",
      gpu: "Integrated graphics",
      cpu: "Intel Core i5 or equivalent",
      hdd: "1 GB (for Roblox Studio)",
    },
  },
  {
    id: 38,
    title: "Skull and Bones",
    price: "49.99",
    description:
      "Skull and Bones is a naval warfare action game set in the Golden Age of Piracy, where players captain their own ship and engage in fierce battles on the high seas. Embark on a pirate adventure across the Indian Ocean, raid merchant ships, and compete against rival pirate factions for dominance. Customize your ship with powerful weapons and upgrades, form alliances or betray your allies, and become the ultimate pirate legend in this multiplayer-focused maritime adventure.",
    brand: "Ubisoft",
    genre: "Action, Naval Warfare",
    imageSrc: "./Assets/Images/medium Card Size/SkullAndBones.png",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 960 / AMD Radeon R9 280X",
      cpu: "Intel Core i5-2500K / AMD FX-8320",
      hdd: "50 GB",
    },
  },
  {
    id: 39,
    title: "Spider-Man: Miles Morales",
    price: "49.99",
    description:
      "Spider-Man: Miles Morales is an action-adventure game set in the Marvel Universe, where players take on the role of Miles Morales as he balances life as a high school student and a superhero. Harness unique abilities such as bio-electric venom blasts and camouflage to thwart crime and protect the city of New York. With its thrilling web-swinging mechanics, cinematic storytelling, and diverse cast of characters, Spider-Man: Miles Morales delivers an immersive superhero experience that celebrates diversity and heroism.",
    brand: "Insomniac Games",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/SpiderManMilesMorals.jpg",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 1060 / AMD Radeon RX 580",
      cpu: "Intel Core i5-7500 / AMD Ryzen 3 1300X",
      hdd: "50 GB",
    },
  },
  {
    id: 40,
    title: "Star Wars: Outlaws",
    price: "59.99",
    description:
      "Star Wars: Outlaws is an action-packed adventure game set in the expansive Star Wars universe. Join a band of smugglers, bounty hunters, and outlaws as they navigate the galaxy's criminal underworld. Encounter iconic Star Wars characters, pilot legendary starships, and engage in epic space battles against the Empire and other factions. With its immersive storytelling, diverse planets to explore, and thrilling dogfights, Star Wars: Outlaws offers fans an unforgettable journey through a galaxy far, far away.",
    brand: "Lucasfilm Games",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/StarWarsOutlaws.png",
    requirements: {
      ram: "16 GB",
      gpu: "NVIDIA GeForce GTX 1060 / AMD Radeon RX 580",
      cpu: "Intel Core i7-6700 / AMD Ryzen 5 1600",
      hdd: "70 GB",
    },
  },
  {
    id: 41,
    title: "Stray",
    price: "39.99",
    description:
      "Stray is an adventure game where players explore a cyberpunk city as a stray cat equipped with a backpack and a small drone companion. Discover the mysteries of a world populated by robots and holograms, solve puzzles, and navigate through narrow alleys and towering skyscrapers. Use your feline agility to traverse rooftops and interact with the inhabitants of this futuristic metropolis. With its unique premise and captivating atmosphere, Stray offers a fresh take on the adventure genre, blending exploration with the charm of being a stray in a bustling city.",
    brand: "BlueTwelve Studio",
    genre: "Adventure",
    imageSrc: "./Assets/Images/medium Card Size/Stray.jpeg",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 970 / AMD Radeon RX 590",
      cpu: "Intel Core i5-4460 / AMD FX-6300",
      hdd: "5 GB",
    },
  },
  {
    id: 42,
    title: "Tchiya",
    price: "29.99",
    description:
      "Tchiya is a puzzle platformer game where players navigate surreal landscapes and manipulate gravity to solve intricate puzzles. Embark on a journey through dreamlike environments, uncover the mysteries of an ancient civilization, and overcome challenges using gravity-defying mechanics. Immerse yourself in a world of optical illusions and shifting perspectives as you unravel the secrets of Tchiya. With its captivating visuals and mind-bending puzzles, Tchiya offers a unique and immersive gameplay experience for puzzle enthusiasts.",
    brand: "Unknown",
    genre: "Puzzle, Platformer",
    imageSrc: "./Assets/Images/medium Card Size/Tchiya.jpg",
    requirements: {
      ram: "4 GB",
      gpu: "NVIDIA GeForce GTX 660 / AMD Radeon HD 7850",
      cpu: "Intel Core i3-2100 / AMD FX-6300",
      hdd: "10 GB",
    },
  },
  {
    id: 43,
    title: "The Crew: MotorFest",
    price: "49.99",
    description:
      "The Crew: MotorFest is an open-world racing game where players compete in high-octane races across the United States. Customize your cars, participate in street races, and join a diverse community of drivers in a massive multiplayer environment. Explore iconic American landscapes from coast to coast, from bustling cities to scenic highways, and discover hidden challenges and collectibles along the way. With its seamless online integration and extensive vehicle customization options, The Crew: MotorFest offers an adrenaline-fueled experience for racing enthusiasts.",
    brand: "Ubisoft",
    genre: "Racing",
    imageSrc: "./Assets/Images/medium Card Size/TheCrewMotorFest.png",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 760 / AMD Radeon R9 280X",
      cpu: "Intel Core i5-4690K / AMD FX-8350",
      hdd: "50 GB",
    },
  },
  {
    id: 44,
    title: "The Last of Us",
    price: "19.99",
    description:
      "The Last of Us is a critically acclaimed action-adventure game that follows Joel and Ellie, two survivors of a devastating pandemic that has ravaged the world. Navigate through post-apocalyptic landscapes, scavenge for resources, and confront hostile human survivors and mutated creatures infected by the Cordyceps fungus. With its emotionally gripping storyline, intense combat sequences, and cinematic presentation, The Last of Us explores themes of survival, loyalty, and the bond between Joel and Ellie in a world where every decision comes with consequences.",
    brand: "Naughty Dog",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/TheLastOfUs.jpg",
    requirements: {
      ram: "4 GB",
      gpu: "NVIDIA GeForce GTX 260 / AMD Radeon HD 5770",
      cpu: "Intel Core i3-3220 / AMD A8-7600",
      hdd: "50 GB",
    },
  },
  {
    id: 45,
    title: "Uncharted 4: A Thief's End",
    price: "39.99",
    description:
      "Uncharted 4: A Thief's End is a thrilling action-adventure game that follows Nathan Drake, a retired treasure hunter, as he is forced back into the world of thieves to uncover a legendary pirate treasure. Join Nathan and his allies on a globe-trotting journey across exotic landscapes, solve intricate puzzles, and engage in heart-pounding gunfights. With its cinematic storytelling, breathtaking visuals, and exhilarating gameplay, Uncharted 4 delivers a fitting conclusion to the beloved series, blending exploration, action, and narrative into an unforgettable adventure.",
    brand: "Naughty Dog",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/Uncharted4.jpg",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 660 / AMD Radeon 7870",
      cpu: "Intel Core i5-2500 / AMD FX-6100",
      hdd: "50 GB",
    },
  },
  {
    id: 46,
    title: "Valorant",
    price: "Free to Play",
    description:
      "Valorant is a tactical first-person shooter where players participate in intense 5v5 matches using a roster of unique characters known as Agents. Each Agent possesses distinct abilities that can turn the tide of battle, from deploying barriers to unleashing powerful ultimates. Coordinate with your team, strategize your approach, and outsmart opponents in a competitive multiplayer environment. With its precise gunplay mechanics, strategic depth, and emphasis on teamwork, Valorant offers a rewarding experience for FPS enthusiasts looking for a blend of skill and strategy.",
    brand: "Riot Games",
    genre: "First-person shooter",
    imageSrc: "./Assets/Images/medium Card Size/Valorant.webp",
    requirements: {
      ram: "4 GB",
      gpu: "NVIDIA GeForce GTX 1050 Ti / AMD Radeon RX 560",
      cpu: "Intel Core i3-3700 / AMD FX-4100",
      hdd: "10 GB",
    },
  },
  {
    id: 47,
    title: "XDefiant",
    price: "Free to Play",
    description:
      "XDefiant is a fast-paced arena shooter that combines intense gunplay with unique character classes inspired by Tom Clancy's universe. Choose from factions like Wolves, Outcasts, Cleaners, and Echelon, each with their own abilities and playstyles. Engage in 6v6 matches across dynamic maps, utilize teamwork and strategy to dominate the opposition, and customize your loadout to suit your preferred playstyle. With its competitive multiplayer action and diverse roster of characters, XDefiant offers a fresh take on the shooter genre for fans of tactical gameplay.",
    brand: "Ubisoft",
    genre: "First-person shooter",
    imageSrc: "./Assets/Images/medium Card Size/XDefiant.png",
    requirements: {
      ram: "8 GB",
      gpu: "NVIDIA GeForce GTX 960 / AMD Radeon R9 280X",
      cpu: "Intel Core i5-2500K / AMD FX-8320",
      hdd: "20 GB",
    },
  },
  {
    id: 48,
    title: "Zelda",
    price: "59.99",
    description:
      "Zelda is an action-adventure game that follows Link, a courageous hero tasked with rescuing Princess Zelda and saving the kingdom of Hyrule from the clutches of the evil Ganondorf. Embark on a quest filled with dungeons, puzzles, and mythical creatures as you wield powerful weapons like the Master Sword and explore vast landscapes. Solve environmental puzzles, discover hidden secrets, and unlock the power of ancient relics to defeat Ganon and restore peace to the land. With its rich lore, captivating gameplay, and iconic characters, Zelda has become a timeless classic in the world of gaming.",
    brand: "Nintendo",
    genre: "Action, Adventure",
    imageSrc: "./Assets/Images/medium Card Size/Zelda.jpg",
    requirements: {
      ram: "4 GB",
      gpu: "NVIDIA GeForce GTX 960 / AMD Radeon R9 270",
      cpu: "Intel Core i5-4460 / AMD FX-6300",
      hdd: "13 GB",
    },
  },
];
